GET https://chat-app-backend-one-iota.vercel.app/

//                          create
### 
GET https://chat-app-backend-one-iota.vercel.app/create?name=muteeb5&email=muteeb@email.com&password=muteeb

### Add additional users if needed
GET https://chat-app-backend-one-iota.vercel.app/create?name=nabeel1234&email=nabeel@email.com&password=nabeel

### 
GEThttps://chat-app-backend-one-iota.vercel.app/create?name=ahsan&email=ahsan@email.com&password=ahsan

//                          duplicate user
###
GET https://chat-app-backend-one-iota.vercel.app/create?name=muteeb&email=muteeb@email.com&password=muteeb


//                           read all
###
GET https://chat-app-backend-one-iota.vercel.app/all

//                          read
###
GET https://chat-app-backend-one-iota.vercel.app/read?email=muteeb@email.com


//                          update
### Change your name
GET https://chat-app-backend-one-iota.vercel.app/update?name=muteeb&email=helo@email.com

//                          delete
### Deleting your entry
GET https://chat-app-backend-one-iota.vercel.app/delete?email=muteeb@email.com

### Read all entries after deletion
GET https://chat-app-backend-one-iota.vercel.app/all

### Delete all user
GET https://chat-app-backend-one-iota.vercel.app/deleteAll?

### Check remaining entries
GET https://chat-app-backend-one-iota.vercel.app/all

